### ISSUE TITLE
[TODO] Implement stamp button

### ISSUE THREAD

**Issue by Gumball12** [guuppy/guuppy-application#1]
## Need

- [x] default image
- [x] clickable *(option)*
- [x] give display info text property *(option)*
- [x] give size setting *(option)*
- [x] give shadow *(option)*
- [x] image opacity *(default: 1)*
- ~give large button *(option)*~
- ~image changeable *(option)*~
