### ISSUE TITLE
[TODO] change readme

### ISSUE THREAD

**Issue by Gumball12** [guuppy/guuppy-application#10]
## needs

- [ ] remove flutter readme template
- [ ] append components list
- [ ] append page lists (with components)
- [ ] introduce guuppy application
