### ISSUE TITLE
[TODO] implement stamp page

### ISSUE THREAD

**Issue by Gumball12** [guuppy/guuppy-application#12]
## needs

- [ ] auto attendance check logic with info msg
- [ ] *go out* button
- [ ] *use stamp* button
- [ ] show goods-modal when click the *use stamp* button
- [ ] show goods in goods-modal (all items clickable)
- [ ] purchase logic (check user stamps)
- [ ] 

## flows
