### ISSUE TITLE
[TODO] Implement stamp list

### ISSUE THREAD

**Issue by Gumball12** [guuppy/guuppy-application#2]
## Need

- [x] stamp length(horizontal) *(default: 1)*
- [x] stamp margin *(default: 10)*
- [x] `StampButton` constructor arguments
- ~horizontal/vertical alignment *(default: left/left)*~
