### ISSUE TITLE
[TODO] implement number pad

### ISSUE THREAD

**Issue by Gumball12** [guuppy/guuppy-application#4]
## needs

- [x] data bind (num pad btn <-> view)
- [x] input mask *(default format: 000-0000-0000)*
- [x] auto-resizing for display resolution
- [x] set button size
- [x] set viewer text style
- [x] set button text style
-  ~set font size~
