### ISSUE TITLE
[TODO] implement policy descriptor

### ISSUE THREAD

**Issue by Gumball12** [guuppy/guuppy-application#5]
## needs

- [ ] get policy text from api server
- [ ] distinguish title and contents
- [ ] add aggrement field
