### ISSUE TITLE
[TODO] Implement main page

### ISSUE THREAD

**Issue by Gumball12** [guuppy/guuppy-application#8]
## needs

- [ ] show stamps
- [ ] screen touch event handling
- [ ] show modal (policies, phone number pad viewer)
- [ ] policies agreement (in modal)
- [ ] phone number validation

## flows

1. user has touched screen
1. show policies and phone number pad viewer
1. user checks policies and enters the phone number
1. if the phone number is valid, redirect to the `stamp page`
